FromDoppler/doppler-beplic

doppler-beplic/doppler-beplic.csproj
remove Microsoft.CodeAnalysis package
=> [No-ticket] - remove CodeAnalysis Package

doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/BeplicService.cs
I'm adding the beplic SDK as a singleton to maintain the access token and expiration date in memory, and avoid getting a new token with every interaction.
Looking forward for your reviews! 🙂
=> [DOI-1005] Add beplic SDK as singleton

doppler-beplic/Models/Config/ApiConnectionOptions.cs, doppler-beplic/Models/Config/DefaultValuesoptions.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/appsettings.Development.json, doppler-beplic/appsettings.json, doppler-beplic/appsettings.qa.json
Added values to the appsettings files.
Also, I applied changes to make use of the appsettings.secret.json file of the stack. I have yet to test this.
In general I struggled a bit when naming classes, settings names, etc. if you can pay attention to that too I would realy apreciate it.
=> [DOI-1008] Add default values in appsettings files

DopplerBeplic.Tests/AuthorizationTest.cs, doppler-beplic/DopplerSecurity/ConfigureDopplerSecurityOptions.cs, doppler-beplic/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs, doppler-beplic/DopplerSecurity/IsSuperUserAuthorizationHandler.cs, doppler-beplic/Models/Config/DefaultValuesoptions.cs, doppler-beplic/Models/DTO/UserCreationDTO.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/appsettings.int.json, doppler-beplic/doppler-beplic.csproj
I applyed some changes sugested by Andres and some other changes.
I recommend reviewing commit by commit.
=> [DOI-1019] Refactoring 

DopplerBeplic.Tests/AuthorizationTest.cs, doppler-beplic/Models/DTO/CustomerUpdateDTO.cs, doppler-beplic/Models/DTO/UserAdminUpdateDTO.cs, doppler-beplic/Models/Responses/CustomerUpdateResponse.cs, doppler-beplic/Models/Responses/UserAdminUpdateResponse.cs, doppler-beplic/Models/Responses/UserCreationResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
New endpoints for update user and customer
=> [DOI-1020] New endpoints for update user and customer

DopplerBeplic.Tests/AuthorizationTest.cs, doppler-beplic/Models/Config/DefaultValuesoptions.cs, doppler-beplic/Models/DTO/UserCreationDTO.cs, doppler-beplic/Services/Classes/BeplicService.cs
Apply create account endpoint updates
=> chore: apply create account endpoint updates

doppler-beplic/Models/Config/DefaultValuesoptions.cs, doppler-beplic/Services/Classes/BeplicService.cs
=>  [DOI-1071]  Set default address if null 

doppler-beplic/Models/Config/DefaultValuesoptions.cs
Set default value for empty address
=> [DOI-1071] Set default value for empty address

doppler-beplic/Models/Config/DefaultValuesoptions.cs, doppler-beplic/Services/Classes/BeplicService.cs
Set default values for empty properties
=> [DOI-1071] Set default values for empty properties

doppler-beplic/Program.cs
Change update endpoints response
=> [DOI-1072] Change update endpoints response 

doppler-beplic/Services/Classes/BeplicService.cs
Fix response access token in account creation
=> [No Ticket] Fix response access token in account creation

doppler-beplic/Services/Classes/BeplicService.cs
=> [DOI-1098] Set default values for plan

doppler-beplic/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs, doppler-beplic/DopplerSecurity/IsSuperUserAuthorizationHandler.cs, doppler-beplic/Logging/LogglySetup.cs, doppler-beplic/Logging/SerilogSetup.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/appsettings.Development.json, doppler-beplic/appsettings.json, doppler-beplic/doppler-beplic.csproj
~~TODO: Add CustomerToken secret to swarm stack~~ https://github.com/MakingSense/doppler-swarm/pull/818
=> [DOI-1096] Add logging

DopplerBeplic.Tests/GetRoomsTests.cs, doppler-beplic/Models/Responses/BeplicResponses/BeplicRoomResponse.cs, doppler-beplic/Models/Responses/RoomResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
Add method to get whatsapp rooms from beplic API. 
Related to doppler automation whatsapp [tasks](https://makingsense.atlassian.net/browse/DOP-1588)
=> Get whatsapp rooms

DopplerBeplic.Tests/GetTemplatesTests.cs, doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateResponse.cs, doppler-beplic/Models/Responses/TemplateResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
Add method to get whatsapp rooms from beplic API.
Related to doppler automation whatsapp [tasks](https://makingsense.atlassian.net/browse/DOP-1588)
=> Get whatsapp templates

doppler-beplic/Services/Classes/BeplicService.cs
Minor changes to fix error messages
=> fix error messages

DopplerBeplic.Tests/SendTemplateMessageTests.cs, doppler-beplic/Models/DTO/TemplateMessageDTO.cs, doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateMessageResponse.cs, doppler-beplic/Models/Responses/TemplateMessageResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
Add methods to send whatsapp template message with beplic API.
Related to doppler automation whatsapp [tasks](https://makingsense.atlassian.net/browse/DOP-1588)
=> Send template message

doppler-beplic/appsettings.json
Task: [DAT-2122](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2122)
[DAT-2122]: https://makingsense.atlassian.net/browse/DAT-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2122] Update url for production

doppler-beplic/Services/Classes/BeplicService.cs
Add logs to know errors from beplic on production environment
=> Add logs for errors

doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/RestClientExtensions.cs
I've added extension to RestClient so we avoid duplicate methods. 
We could consider use some factory to get clients properly
=> Add RestClientExtensions

doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateResponse.cs, doppler-beplic/Models/Responses/TemplateResponse.cs, doppler-beplic/Services/Classes/BeplicSdk.cs, doppler-beplic/Services/Classes/BeplicService.cs
Include generated preview url on get templates
=> Add template preview

doppler-beplic/Services/Classes/BeplicService.cs
Filter templates to work with only approved templates by meta
=> Add template filter

doppler-beplic/Models/Responses/PlanResponse.cs
Add new property on response for free plans
=> Add IsFree property

doppler-beplic/Models/Responses/BeplicResponses/BeplicUserPlanResponse.cs, doppler-beplic/Models/Responses/UserPlanResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
Add a new method to get a user plan using the external id
=> Get user plan

doppler-beplic/Models/Responses/TemplateResponse.cs, doppler-beplic/Services/Classes/BeplicService.cs
Add header parameter in template response. To use on multimedia templates sending
=> Update template response

doppler-beplic/Models/DTO/TemplateMessageDTO.cs, doppler-beplic/Services/Classes/BeplicService.cs
Add new header type parameter to send multimedia templates
=> chore: allow header type by parameter

doppler-beplic/Services/Classes/BeplicService.cs
Remove unused parameters on preview url
=> Change on preview url generation

DopplerBeplic.Tests/GetTemplateMessageStatusTests.cs, doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateMessageStatusResponse.cs, doppler-beplic/Models/Responses/TemplateMessageResponse.cs, doppler-beplic/Models/Responses/TemplateMessageStatusResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
Add new method to get status for whatsapp messages with tests
=> Add get message status

doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateMessageStatusDetailResponse.cs, doppler-beplic/Models/Responses/BeplicResponses/BeplicTemplateMessageStatusResponse.cs, doppler-beplic/Models/Responses/TemplateMessageStatusResponse.cs, doppler-beplic/Services/Classes/BeplicService.cs
Add new beplic responses classes and format the response
=> Add detail on message status response

DopplerBeplic.Tests/GetConversationsByExternalIdAndDatesTests.cs, doppler-beplic/Models/Responses/ConversationCountResponse.cs, doppler-beplic/Models/Responses/GetConversationsByCustomerAndDatesResponse.cs, doppler-beplic/Program.cs, doppler-beplic/Services/Classes/BeplicService.cs, doppler-beplic/Services/Interfaces/IBeplicService.cs
Integrate endpoint to get the conversation for the externalId and dates with beplic endpoint.
**Task:** [DAT-2378](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2378)
[DAT-2378]: https://makingsense.atlassian.net/browse/DAT-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2378] - Integrate endpoint to get the conversation for the externalId and dates with beplic endpoint
